name: Crear imagen Docker

on:
  push:
    branches: 
      - 'main'
permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.get_version.outputs.version }} #tag será un output
      artifactID: ${{ steps.get_artifact.outputs.version }} #ARTIFACTID

    steps:
        
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get version from package.json
        id: get_version
        run: | 
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
          
      - name: Get random artifact ID
        id: get_artifact
        run: | 
          echo "IMAGE_TAG=$(date '+%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT

  call-ci-workflow:
    needs: build #para traer el output
    uses: ./.github/workflows/ci-reusable.yml
    with:
      tag: ${{ needs.build.outputs.tag }} #input para el workflow reusable: la versión del proyecto
    secrets:
      dockeruser: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerpassword: ${{ secrets.DOCKERHUB_TOKEN }}
