name: Publish to Docker
on:
  workflow_call:
    inputs: 
      tag:
        required: true
        type: string
    secrets:
      dockeruser:
        required: true
      dockerpassword:
        required: true

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write
  
jobs:
   publish:
    runs-on: ubuntu-latest
    #environment: 
      #name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockeruser }}
          password: ${{ secrets.dockerpassword }} 
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: eperezstemdo/git-action-project-davie-elisa/angulaimage
          tags: eperezstemdo/angularimage:${{ inputs.tag }}
          
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: eperezstemdo/angularimage:${{ inputs.tag }}

         
