name: Workflow CD caller
on:
  pull_request:
    types: [closed]
    branches: 
      - 'main'
jobs:     
  call-reusable-workflow:
    uses: ./.github/workflows/workflow_CD_reusable.yml
    with:
      image-to-build: eperezstemdo/angularimage:0.0.0-snapshot
